buildscript {
    ext {
        springBootVersion = '3.2.2'
        dependencyManagementVersion = '1.1.4'
        javaVersion = JavaVersion.VERSION_21
        gradleVersion = '8.6'
        lombokVersion = '1.18.30'
        jacocoVersion = '0.8.11'
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:${dependencyManagementVersion}"
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${dependencyManagementVersion}"
    id 'jacoco'
}

jacoco {
    toolVersion = "${jacocoVersion}"
}

dependencies {
    implementation project(':app-service')
    implementation('org.springframework.boot:spring-boot-starter-web') {
        exclude group: 'org.apache.tomcat.embed', module: 'tomcat-embed-core'
        exclude group: 'org.apache.tomcat.embed', module: 'tomcat-embed-el'
        exclude group: 'org.apache.tomcat.embed', module: 'tomcat-embed-websocket'
    }

    implementation 'org.apache.tomcat.embed:tomcat-embed-core:10.1.34'
    implementation 'org.apache.tomcat.embed:tomcat-embed-el:10.1.34'
    implementation 'org.apache.tomcat.embed:tomcat-embed-websocket:10.1.34'
}

group = 'co.com.nelumbo.backpmo'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of("${javaVersion}")
    }
    sourceCompatibility = "${javaVersion}"
    targetCompatibility = "${javaVersion}"
}

wrapper {
    gradleVersion = "${gradleVersion}"
    distributionType = Wrapper.DistributionType.ALL
}

apply from: './main.gradle'

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    finalizedBy jacocoMergedReport
    reports {
        xml.required = true
        csv.required = false
        html.destination layout.buildDirectory.file("jacocoHtml").get().asFile
    }
}

bootJar {
    dependsOn test
    manifest {
        attributes 'Start-Class': 'com.example.demo.DemoApplication'
    }
}
