dependencyResolutionManagement {
    versionCatalogs {
        libs {
            version('mapstruct', '1.5.5.Final')
            version('jakartaAnnotation', '2.1.1')
            version('jakartaValidation', '3.0.2')
            library('mapstructCore', 'org.mapstruct', 'mapstruct').versionRef('mapstruct')
            library('mapstructLombok', 'org.projectlombok:lombok-mapstruct-binding:0.2.0')
            library('jpa', 'org.springframework.boot:spring-boot-starter-data-jpa:3.2.3')
            library('mariadb', 'org.mariadb.jdbc:mariadb-java-client:3.0.6')
            library('h2Database', 'com.h2database:h2:2.2.224')
            library('mapstructProcessor', 'org.mapstruct', 'mapstruct-processor').versionRef('mapstruct')
            library('jakartaAnnotation', 'jakarta.annotation', 'jakarta.annotation-api').versionRef('jakartaAnnotation')
            library('jakartaValidation', 'jakarta.validation', 'jakarta.validation-api').versionRef('jakartaValidation')
        }
    }
}

include 'infrastructure'
include 'app-service'
include 'domain'
include 'application'
